version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs:rw
      - .:/bot:ro
    tty: true
    env_file:
      - .env
    init: true
    restart: always
    networks:
      - common-shared-network

networks:
  common-shared-network:
